### ISSUE TITLE
Reproduce the results

### ISSUE THREAD

**Issue by tqosu** [ZijiaLewisLu/CVPR2024-FACT#1]
Hi Zijia,
Do I need to change anything to reproduce the results?
There is a big difference between the provide cpkts and the best_ckpt.gz for GTEA split1:
{'Edit': 82.32968488500221, 'AccB': 80.41712403951702, 'Acc': 80.41712403951702, 'F1@0.10': 84.91829098973291, 'F1@0.25': 82.59810548263115, 'F1@0.50': 69.14102954154987}
{'Edit': 94.19007603041216, 'AccB': 83.62239297475303, 'Acc': 87.71854399541415, 'F1@0.10': 94.69646252559737, 'F1@0.25': 93.18131112527297, 'F1@0.50': 84.84797842351622}

**Comment by ZijiaLewisLu** [comment]
Hi, 

Thanks for your comments. There seems to be an issue in the code. I am looking into it.

**Comment by ZijiaLewisLu** [comment]
Hi,

I corrected an error in the evaluation code. Please pull the latest code and run again. Meanwhile, gtea is small and its results can fluctuate. We took multiple runs and took the best one. You can also try breakfast for replication.
