### ISSUE TITLE
How to get video feature

### ISSUE THREAD

**Issue by ymzhang0319** [ZijiaLewisLu/CVPR2024-FACT#2]
Thanks for your nice work!

I'd like to train FACT on other dataset. Please tell me how to get the video feature for training!

**Comment by ZijiaLewisLu** [comment]
Hi, 

Thanks for your interest. We use I3D-Resnet model to compute features for EgoProceL, which has similar performance as I3D and avoids computing optical flows. You can use the `extract_from_frame.py` or `extract_from_video.py` from [this repo](https://github.com/ZijiaLewisLu/action-recognition-pytorch). It is a fork of the original paper code. It computes framewise features via sliding window.

**Comment by ymzhang0319** [comment]
@ZijiaLewisLu Thanks for your reply!
