### ISSUE TITLE
Could you release the paper to help us understand your wonderful method? 

### ISSUE THREAD

**Issue by labGoku** [ZijiaLewisLu/CVPR2024-FACT#3]
Could you release the paper to help us understand your wonderful method?  Thank you very much

**Comment by ZijiaLewisLu** [comment]
Hi,

Thanks for your interest. the paper can be found here: https://openaccess.thecvf.com/content/CVPR2024/papers/Lu_FACT_Frame-Action_Cross-Attention_Temporal_Modeling_for_Efficient_Action_Segmentation_CVPR_2024_paper.pdf.
