### ISSUE TITLE
Request for Clarification on Repository Code License

### ISSUE THREAD

**Issue by yu-xi-wang** [ZijiaLewisLu/CVPR2024-FACT#5]
Thank you for your excellent work on this project! I would like to kindly ask for clarification regarding the license under which the code in this repository is distributed. 
Looking forward to your response.

Best regards,

**Comment by ZijiaLewisLu** [comment]
Hi,

Thanks for your interest! The code can be distributed under MIT License.

**Comment by yu-xi-wang** [comment]
Thank you for the clarification!

Best regards
